"""quantity

Revision ID: 253081b80c01
Revises: ddbad102b213
Create Date: 2023-09-27 16:26:09.461926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253081b80c01'
down_revision: Union[str, None] = 'ddbad102b213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'created_at',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
