"""new migration

Revision ID: ddbad102b213
Revises: 8230c1a2176b
Create Date: 2023-09-27 16:22:20.069965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbad102b213'
down_revision: Union[str, None] = '8230c1a2176b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.alter_column('products', 'created_at',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
